name: CI

env:
    CI: true

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
            - '[0-9]*'

jobs:
    build-test:
        strategy:
            max-parallel: 1
            fail-fast: true
            matrix:
                operating-system: ['ubuntu-latest', 'macos-latest']
                php-versions: ['8.1', '8.2', '8.3']

        runs-on: ${{ matrix.operating-system }}

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }})

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Libraries
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                        sudo apt-get install -y coreutils
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                        brew install coreutils
                  elif [ "$RUNNER_OS" == "Windows" ]; then
                        choco install busybox -y
                  fi
              shell: bash

            - name: PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  extensions: fileinfo, mysqli, xdebug, mbstring, xmlrpc, gd, intl, xml, zip, soap, bcmath, imap, opcache, pgsql, pdo, imagick
                  tools: composer, phpunit

            - name: Composer
              run: composer install --no-interaction

            - name: Create config.json from secret
              run: echo "${{ secrets.CONFIG_JSON_BASE64 }}" | base64 -d > config.json

            - name: PHPUnit
              run: ./vendor/bin/phpunit
